### ISSUE TITLE
Visited Switch is not accessible in iOS

### ISSUE THREAD

**Issue by MEFTEK-LLC** [MEFTEK-LLC/mbma-public#1]
The visited switch in the details screen is overlaided by the status icon and the switch cannot be toggled.  

Example: Motor City Brewing Works,  Livernois has this issue.

![39B46771-3695-4F82-83EB-1489DD52C7B0](https://user-images.githubusercontent.com/111077835/215128452-15880b2c-9282-4be1-a53d-4947e61eba7e.jpeg)

**Comment by bcarney66** [comment]
Tested in 4.0.3 (34) iOS, and it works as intended.
