### ISSUE TITLE
Some Breweries are missing Hours

### ISSUE THREAD

**Issue by MEFTEK-LLC** [MEFTEK-LLC/mbma-public#3]
Motor City Brewing Works-Livernois and Cadillac Straits are 2 examples

**Comment by bcarney66** [comment]
Spot checked some more and found one more commonality - any entry that has a "Message from brewery" is missing the Hours section in iOS.  It's as if that box is overtop where the hours should be displayed.

**Comment by bcarney66** [comment]
Tested in 4.0.3 (34) iOS, and it works as intended.
